name: Deploy

on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.19.0

      - uses: actions/setup-node@v3.5.1
        with:
          node-version: 18.12.1
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - run: pnpm test:types
      - run: BASE_URL=/tinkoff-solutioncup-frontend/ pnpm build

      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          # Upload dist repository
          path: "./dist"
      - uses: actions/deploy-pages@v1
        id: deployment
